server:
  port: 8083

spring:
  application:
    name: task
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: task
    show-sql: true
    open-in-view: false
    generate-ddl: true
  flyway:
    url: jdbc:postgresql://localhost:5432/task
    user: postgres
    password: password
    schemas: task
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

logging:
  level:
    root: info
    web: trace
